manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 3b4d6c38c0df837ddf617b8e37e1e5c11a4da4fe
      import: app/west.yml
  self:
    path: config